### ISSUE TITLE
Project status, in particular pure HTML5 

### ISSUE THREAD

**Issue by Utopiah** [scratchfoundation/scratchjr#557]
Hi, apologies if this isn't the right place to ask but I didn't see any update for the last few months. I'm wondering if the HTML5 version is still in the work and if so if there is any estimation, even if very rough, of when it might get released.

ScratchJr is an amazing project. I believe that opening it up to desktop to run on e.g a RaspberryPi or facilitate sharing without having to install the application could help a lot of newcomers to discover it an participate.

Anyway thanks again for the great work.

**Comment by deepankarmalhan** [comment]
Hey @Utopiah, thank you for opening up the issue! We're working on the web version actively and aim to release it by summer next year (although that deadline is not set in stone so I expect it to change). We'll release more info early next year when we're at a place to start showing people what the web version looks like!
